### PR TITLE
Plotly issue 3232 min

### PR DESCRIPTION
**Pull request by archmoj**
Please refer to [Plotly PR](https://github.com/plotly/plotly.js/pull/3315) for more info.
@etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
cc @dy would you mind taking a :eye: at this?

**Comment by dy** [comment]
@etpinard sure.

@archmoj if I get it right, you just force direct color buffer and skip palette mode? You can just organize passing `tooManyColors` flag via `update` method, for plotly-specific case. Is there a special reason we need to remove palette mode completely?

I can try reproducing this with a test-case, Alex can be right regarding the https://github.com/plotly/plotly.js/pull/2499.

**Comment by dy** [comment]
@archmoj @etpinard ok, seems to have fixed this issues in https://github.com/gl-vis/regl-scatter2d/pull/15, here is the baseline https://github.com/gl-vis/regl-scatter2d/blob/74a1e4486b7968a9c4648e95b9c2138a2f0840a1/test/img/3232.png. The was just extra number of colors.

**Comment by etpinard** [comment]
@dy great!

Will you attempt to fix https://github.com/gl-vis/regl-scatter2d/pull/15#issuecomment-441273649, should we (myself or @archmoj ) try to bring #15 to the (plotly.js) finish line?

**Comment by dy** [comment]
@etpinard sure, I can try to figure out where the `const` comes form, that should not be there.

**Comment by dy** [comment]
Superceded by #15

**Pull request closed without merging**
