### PR TITLE
Fix missing points

### LINKED ISSUE #2334: Missing data in scattergl plot when I go juste above 10000 points (regression)
Hi,

I just updated plotly.js from 1.30 to the latest 1.33, and my plot is broken.

I’m rendering about 75000 points with a scattergl plot, and after the update, it looks like most of the points are not rendered at all. What is odd though, is that when I hover over the plot, I can still see popups showing when my mouse is over places where points are supposed to be.

After trying different things, I noticed everything is rendering fine up to 10000 data points. If I go just above, say 10001, my plot is broken and most of the points are not rendered!

Everything worked fine with plotly.js 1.30.

I made two versions of my code, one with 10000 points, and the other with 10001. See for yourself: https://0.x2a.yt/other/private/plotly-test/10000.html
https://0.x2a.yt/other/private/plotly-test/10001.html

(This bug report is a copy/paste from the following forum topic: https://community.plot.ly/t/regression-missing-data-in-scattergl-plot-when-i-go-juste-above-10000-points/8152)

### PR DESCRIPTION
**Pull request by dy**
This fixes https://github.com/plotly/plotly.js/issues/2334 and related issues.

Turns out there was overflow in point-cluster, fixed in 3.1.5 https://github.com/dy/point-cluster/commit/bdda757def9481be00cb886298e48c0929ee5186

cc @etpinard @archmoj

### CODE REVIEW

**Comment by archmoj** [comment]
Thanks @dy for the fix.
Once I tried this branch on `Plotly.js`, I was not able to spot any difference using the [Before](https://codepen.io/MojtabaSamimi/pen/pYwQoj) and [After](https://codepen.io/MojtabaSamimi/pen/pYwQoj) codepens.
Any suggestion that may help would be much appreciated.

**Comment by dy** [comment]
Ah, I see. Well, point-cluster isn't good with half-transparent points - it just hides points that are overlapped by other points - if you have transparent points, then total transparency can be lost, as it is seen on the edges of the plots you've sent.

The original solution @mikolalysenko had in [snap-points-2d](https://ghub.io/snap-points-2d) was counting number of points in cluster and deriving transparency from that number (`weights` property). Afaik, that wasn't implemented in gl-scatter2d, but that's possible.

That feature is not yet in point-cluster, but actually a good improvement. Can be addressed in a separate issue.

This issue just fixes missing points.

Also CI is broken, urgh.

**Comment by etpinard** [comment]
Thanks very much @dy !

The problem described  https://github.com/plotly/plotly.js/issues/3405 (see https://codepen.io/etpinard/pen/Larwdp) doesn't appear to be fixed though (see https://codepen.io/etpinard/pen/KEeOyB, using @archmoj 's https://28893-45646037-gh.circle-artifacts.com/0/dist/plotly.min.js), some points appear to still be missing. 

@archmoj could you confirm that I'm using the correct bundle in my https://codepen.io/etpinard/pen/KEeOyB codepen?

**Comment by archmoj** [comment]
> @archmoj could you confirm that I'm using the correct bundle in my https://codepen.io/etpinard/pen/KEeOyB codepen?

@etpinard That's the right bundle. I also tested your codepen with rebuilt `regl-scatter2d` bundle locally which displays a similar result after update.

**Comment by dy** [comment]
I have to investigate. Not sure I even understand the issue, so some points are just not displayed?
Can we possibly reproduce test-case here?

**Comment by etpinard** [comment]
> so some points are just not displayed?

Correct.


> Can we possibly reproduce test-case here?

Here's https://codepen.io/etpinard/pen/KEeOyB, going from N pts down to M pts using an update (here `Plotly.react`) call results in less pts than just plotting M pts.

@dy please let us know if you would prefer a pure `regl-scatter2d` reproducible example.

**Comment by dy** [comment]
@etpinard not sure I can grasp the issue, it is whether works fine for me or I just don't get something.
That would be simpler, yes, to come up with reproducible bug as a test-case here (example https://github.com/gl-vis/regl-scatter2d/blob/master/test/index.js#L83-L100)

**Comment by etpinard** [comment]
After clicking `newPlot(N)`:

image


After clicking `newPlot(M)`:

image


After clicking `newPlot(N)` then `react(M)`:

image

------------

> That would be simpler, yes, to come up with reproducible bug as a test-case here

Sure :ok_hand: Not sure if I'll have time to get to it this week, but I'll try.

**Comment by dy** [comment]
Ok, got it. I'll look at that today.

**Comment by dy** [comment]
Hm. That is not what I have in the example:
After clicking `newPlot(N)`:

image


After clicking `newPlot(M)`:
image

After clicking `newPlot(N)` then `react(M)`:
image

I get the same picture in Win10/Win7/Brave/Chromw.

Not sure what do I do wrong here. Is that reproducible on OSX?

**Comment by etpinard** [comment]
@archmoj can you try to reproduce https://github.com/gl-vis/regl-scatter2d/pull/19#issuecomment-474824454 from https://codepen.io/etpinard/pen/KEeOyB ?

Thanks!

**Comment by archmoj** [comment]
> After clicking `newPlot(N)` then `react(M)`:
> image
> 
> I get the same picture in Win10/Win7/Brave/Chromw.
> 
> Not sure what do I do wrong here. Is that reproducible on OSX?

After `newPlot(N)` then `react(M)`  there are too many points in the graph!
From what I see on Windows+Firefox too many points were displayed.
And in MacOS/Ubuntu+Firefox/Chrome many points are missing!

**Comment by archmoj** [comment]
@dy would you still be interested in bringing this PR to the finish line?
You mentioned a bug fixed in `point-cluster` module which is obviously a good thing to have.
And if you generate the new baselines, @etpinard we can proceed to merge this, right?

**Comment by dy** [comment]
If we could add test-case here, that would be way easier for me to debug.
Not 100% sure that belongs here and not to plotly scattergl trace.
I was going to refactor this component back to gl-scatter2d, in a way similar to [gl-text](https://github.com/plotly/plotly.js/blob/3e15f17b7aa5399bc36655ee5a8da7b1787ca450/src/traces/scattergl/index.js#L251), to avoid updating batch mess, that seems to be more efficient to have a set of lightweight instances, providing we cache them. That would fix the points number difference issue.
As for this PR - pretty sure we can merge it.

**Comment by etpinard** [comment]
> that would be way easier for me to debug.

Absolutely, I'll try to replicate the bug in pure `regl-scatter2d`



> As for this PR - pretty sure we can merge it.


Go for it. :rocket:

**Pull request merged**
